name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  server:
    runs-on:
      - macos-latest
    steps:
      - uses: actions/checkout@v2.2.0
        with:
          fetch-depth: 0

      - name: Setup Clojure
        uses: DeLaGuardo/setup-clojure@3.7
        with:
          cli: 1.10.3.1058

      - name: Setup Babashka
        uses: turtlequeue/setup-babashka@v1.3.0
        with:
          babashka-version: 0.7.0

      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Test
        run: bb test

      - name: Publish assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: bb upload-assets
